### ISSUE TITLE
The problem of closing the connection

### ISSUE THREAD

**Issue by ussoft2011** [duckdb/duckdb-node-neo#73] opened 2024-12-17 03:47 UTC
How should I close the connection? I couldn't find the close method. Please help me, thank you

const instance = await DuckDBInstance.create(backPath, {
            threads: '4'
        });

const  connection = await instance.connect();

**Comment by jraymakers** [comment] 2024-12-17 04:32
Duplicate of #71 and #55.

**Closed by jraymakers** 2024-12-17 04:32 UTC
